### ISSUE TITLE
Pipeline should use the same "Label" for a pipeline run

### ISSUE THREAD

**Issue by johanrydstrom** [AvegaGroup/dockerApplicationServer#21]
**Current state**: DoodleshopBAT shows "Label: 1.0.x" but next step shows "Label: x"
**Desired state**: DoodleshopBAT shows "Label: 1.0.x" and next step(s) shows "Label: 1.0.x"

**Comment by sennerholm** [comment]
Hade helst velat ha dom i separata pull request, 1 för gitignore, 1 för cruise.xml och sedan kanske en för att plocka bort vagrant support.

**Comment by johanrydstrom** [comment]
Så, nu finns separata PR!

**Comment by sennerholm** [comment]
Mergat dom andra, var det något kvar i den här då?

**Comment by johanrydstrom** [comment]
Nope!
