### ISSUE TITLE
Spara undan artifactory data

### ISSUE THREAD

**Issue by sennerholm** [AvegaGroup/dockerApplicationServer#9]
Just nu har vi bara loggar i en volum, vi behöver även datat så vi kan spara det mellan körningar.

Mvh Mikael

**Comment by sennerholm** [comment]
Fungerar nu, men ibland verkar artifactory volymen bli korrupt, kanske byta till nexus istället?

**Comment by FredrikWendt** [comment]
Min erferanhet av Nexus är att det fungerar bra för Maven repos, men vi
använder RPM och .p2 också - och det är inte i närheten av vad man
förväntar sig.
För denna enkla pipe väntar jag mig att båda produkterna fungerar lika bra.
Är det databasen som blir/blev korrupt, eller även artefakterna?

2015-05-12 20:52 GMT+02:00 Mikael Sennerholm <notifications@github.com>:

> Fungerar nu, men ibland verkar artifactory volymen bli korrupt, kanske
> byta till nexus istället?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AvegaGroup/dockerApplicationServer/issues/9#issuecomment-101385860>
> .
>



-- 
+46 702 778511

**Comment by sennerholm** [comment]
Hej!

Tror att det var någon databas, just nu slänger jag den katalogen när jag
kör om.

Mvh Mikael

Den 12 maj 2015 20:55 skrev Fredrik Wendt <notifications@github.com>:

> Min erferanhet av Nexus är att det fungerar bra för Maven repos, men vi
> använder RPM och .p2 också - och det är inte i närheten av vad man
> förväntar sig.
> För denna enkla pipe väntar jag mig att båda produkterna fungerar lika bra.
> Är det databasen som blir/blev korrupt, eller även artefakterna?
>
> 2015-05-12 20:52 GMT+02:00 Mikael Sennerholm <notifications@github.com>:
>
> > Fungerar nu, men ibland verkar artifactory volymen bli korrupt, kanske
> > byta till nexus istället?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/AvegaGroup/dockerApplicationServer/issues/9#issuecomment-101385860
> >
> > .
> >
>
>
>
> --
> +46 702 778511
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AvegaGroup/dockerApplicationServer/issues/9#issuecomment-101387160>
> .
>



-- 
Mikael Sennerholm
+46707401585
